### ISSUE TITLE
Failed connect to gateway on Android 10

### ISSUE THREAD

**Issue by indrian16** [ttlock/Android_SDK_Demo#6]
I have tried to scan the gateway successfully when connecting it crashed, but on Android 9 can and smoothly without obstacles

```
GatewayClient.getDefault().connectGateway(device, object : ConnectCallback {
        override fun onConnectSuccess(device: ExtendedBluetoothDevice?) {
            hideLoading()
            toast("Connected")
            Intent(baseContext, ConfigureNetworkActivity::class.java).apply {
                finish()
                putExtra(ConfigureNetworkActivity.DEVICE_EXTRA, device)
            }.run {
                startActivity(this)
            }
        }

        override fun onDisconnected() {
            hideLoading()
            toast("Disconnected")
        }
    })
```

I get an error on Android 10: at com.ttlock.bl.sdk.gateway.api.c.d(:79)
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
       at android.util.SparseArray.keyAt(SparseArray.java:295)
       at com.ttlock.bl.sdk.gateway.api.c.d(:79)
       at com.ttlock.bl.sdk.gateway.api.GattCallbackHelper$3.run(:424)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

i use sdk ttlock-release-3.0.7
**Thanks in advance!**

**Comment by indrian16** [comment]
It has been helped by the TTLock team, Thanks
